version: '3'

services:
  node-exporter:
    image: "prom/node-exporter:v0.15.2"
    networks:
      - metrics

  prometheus:
    image: "prom/prometheus:v2.0.0"
    networks:
      - metrics
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter

  grafana:
    image: "grafana/grafana:master"
    ports:
      - "3000:3000"
    networks:
      - metrics
    volumes:
        - grafana-data:/var/lib/grafana
        - ./grafana.ini:/etc/grafana/grafana.ini
        - ./datasources.yml:/usr/share/grafana/conf/datasources/datasources.yml
    depends_on:
      - prometheus

networks:
  metrics:

volumes:
  prometheus-data:
  grafana-data:
